CREATE TABLE "T_USER_SETTING"
(
 "USER_ID" VARCHAR(100) NOT NULL,
 "COVER" VARCHAR(1024) NULL,
 "UPDATE_DT" TIMESTAMP(0) NOT NULL
);

CREATE TABLE "T_TIMELINE"
(
 "ID" INT IDENTITY(1434,1) NOT NULL,
 "FEED_ID" VARCHAR(32) NOT NULL,
 "ORG_ID" VARCHAR(32) NOT NULL,
 "CREATE_DT" TIMESTAMP(0) NOT NULL,
 "FEED_STATUS" INT NOT NULL
);

CREATE TABLE "T_MESSAGE"
(
 "ID" INT IDENTITY(8625,1) NOT NULL,
 "MESSAGE_ID" VARCHAR(64) NOT NULL,
 "FEED_ID" VARCHAR(64) NOT NULL,
 "USER_ID" VARCHAR(64) NOT NULL,
 "MESSAGE_TYPE" INT NOT NULL,
 "STATUS" INT NOT NULL,
 "CREATE_DT" TIMESTAMP(0) NOT NULL,
 "PUBLISH_USER_ID" VARCHAR(64) NOT NULL
);

CREATE TABLE "T_LIKE"
(
 "ID" BIGINT IDENTITY(1046,1) NOT NULL,
 "LIKE_ID" VARCHAR(100) NOT NULL,
 "FEED_ID" VARCHAR(100) NOT NULL,
 "USER_ID" VARCHAR(100) NOT NULL,
 "CREATE_DT" TIMESTAMP(0) NOT NULL,
 "LIKE_STATUS" INT NOT NULL
);

CREATE TABLE "T_FEED"
(
 "ID" INT IDENTITY(1454,1) NOT NULL,
 "FEED_ID" VARCHAR(64) NOT NULL,
 "USER_ID" VARCHAR(64) NOT NULL,
 "FEED_TYPE" INT NOT NULL,
 "FEED_CONTENT" TEXT NOT NULL,
 "FEED_POI" VARCHAR(255) NULL,
 "FEED_STATUS" INT DEFAULT 0
 NOT NULL,
 "CREATE_DT" TIMESTAMP(0) NOT NULL,
 "UPDATE_DT" TIMESTAMP(0) NOT NULL
);

CREATE TABLE "T_COMMENT"
(
 "ID" BIGINT IDENTITY(3309,1) NOT NULL,
 "COMMENT_ID" VARCHAR(100) NOT NULL,
 "FEED_ID" VARCHAR(100) NOT NULL,
 "USER_ID" VARCHAR(100) NOT NULL,
 "COMMENT_CONTENT" VARCHAR(1000) NULL,
 "REPLY_TO" VARCHAR(100) NULL,
 "CREATE_DT" TIMESTAMP(0) NOT NULL
);

ALTER TABLE "T_USER_SETTING" ADD CONSTRAINT  PRIMARY KEY("USER_ID") ;

ALTER TABLE "T_TIMELINE" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "T_MESSAGE" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "T_LIKE" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "T_FEED" ADD CONSTRAINT  PRIMARY KEY("ID") ;

ALTER TABLE "T_COMMENT" ADD CONSTRAINT  PRIMARY KEY("ID") ;

CREATE INDEX "TIMELINE_KEY_ORG_ID"
ON "T_TIMELINE"("ORG_ID");

CREATE INDEX "MESSAGE_KEY_MESSAGE_ID"
ON "T_MESSAGE"("MESSAGE_ID");

CREATE INDEX "MESSAGE_KEY_USER_ID"
ON "T_MESSAGE"("USER_ID");

CREATE UNIQUE INDEX "LIKE_UNIDX_LIKE_ID"
ON "T_LIKE"("LIKE_ID");

CREATE UNIQUE INDEX "LIKE_UNIDX_LIKE_FID_UID"
ON "T_LIKE"("FEED_ID","USER_ID");

COMMENT ON COLUMN "T_LIKE"."ID" IS '主键';

CREATE INDEX "FEED_KEY_USER_ID"
ON "T_FEED"("USER_ID");

CREATE UNIQUE INDEX "FEED_UNION_KEY_FEED_ID"
ON "T_FEED"("FEED_ID");

COMMENT ON COLUMN "T_FEED"."ID" IS '自增Id';

COMMENT ON COLUMN "T_FEED"."FEED_ID" IS '动态 Id';

COMMENT ON COLUMN "T_FEED"."USER_ID" IS '发布者 Id';

COMMENT ON COLUMN "T_FEED"."FEED_TYPE" IS '动态类型';

COMMENT ON COLUMN "T_FEED"."FEED_CONTENT" IS '动态内容';

COMMENT ON COLUMN "T_FEED"."FEED_POI" IS '动态的地理位置信息';

COMMENT ON COLUMN "T_FEED"."FEED_STATUS" IS '0 正常，1 被删除';

CREATE INDEX "COMMENT_KEY_FID_UID"
ON "T_COMMENT"("FEED_ID","USER_ID");

CREATE UNIQUE INDEX "COMMENT_UNIQUE_COMMENT_ID"
ON "T_COMMENT"("COMMENT_ID");

COMMENT ON COLUMN "T_COMMENT"."ID" IS '主键';

