server:
  port: 8081
  servlet:
    context-path: /api
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
      indent_output: true
      write_null_map_values: false
    deserialization:
      accept_single_value_as_array: true
    default-property-inclusion: non_null
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

## JWT 鉴权配置
jwt:
  secret: "ay9pL#$MomentServer"
  ttlInMilliSec: 8640000000

## 融云 IM 配置
im:
  appKey: xxxxx
  secret: xxxxx
  host: http://127.0.0.1:8081

## 融云 RCE 配置
rce:
  systemUid: fGpg5fuCsF2PWCD4uZ8Dzh
  secret: xxxxx
  host: https://127.0.0.1:8443/api

## 日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    cn.rongcloud: INFO
  file:
    max-history: 8
    name: logs/momentserver.log
    max-size: 100MB
  pattern:
    rolling-file-name: logs/momentserver.%d{yyyy-MM-dd}.%i.gz

# 数据库相关配置
db:
  name: mysql
# Mysql
jdbc:
  url: jdbc:mysql://localhost:3306/momentdb?useUnicode=true
  username: root
  password: 123456
  driver: com.mysql.jdbc.Driver

ds:
  initialSize: 5
  minIdle: 10
  maxActive: 100
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000


##moment工程内部配置

moment:
  pass:
    anonymousUrls:
      - /**/*/user/auth
      - /**/*/misc/version
      - /**/*/doc.html
      - /**/*/webjars/**
      - /**/*/swagger-resources/**
      - /**/*/v2/api-docs
  publish_notify_corn: 0 */1 * * * ?
  system_manager_id: fGpg5fuCsF2PWCD4uZ8Dzh #系统管理员Id
  comment_update:
    delay_pull_time: 0
  moment_update:
    delay_pull_time: 300
  clear_msg:
    interval_days: 30
    cron: 0 0 2 * * ?
  expire:
    comment: 86400000
    like: 86400000
    intervalS: 86400000


swagger2:
  enable: false
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl