server:
  port: 8080
  servlet:
    context-path: /api
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
      indent_output: true
      write_null_map_values: false
    deserialization:
      accept_single_value_as_array: true
    default-property-inclusion: non_null
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

## JWT 鉴权配置
jwt:
  secret: "ay9pL#$MeetingServer"
  ttlInMilliSec: -1

## 融云 IM 配置
im:
  appKey: xxx
  secret: xxxx
  host: http://api-cn.ronghub.com

## 日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    cn.rongcloud: INFO
  file:
    max-history: 8
    name: logs/momentserver.log
    max-size: 100MB
  pattern:
    rolling-file-name: logs/momentserver.%d{yyyy-MM-dd}.%i.gz

## MeetingServer 配置
meetingserver:
  adminUserId: DLMrJ9prNw2vcl0MJavRClK

# 数据库相关配置
db:
  name: mysql
# Mysql
jdbc:
  url: jdbc:mysql://localhost:3306/momentdb?useUnicode=true
  username: root
  password: 123456
  driver: com.mysql.jdbc.Driver

# DM
#jdbc:
#  url: jdbc:dm://localhost:3306/meetingdb?useUnicode=true
#  username: root
#  password: 123456
#  driver: dm.jdbc.driver.DmDriver

## Kingbase
#jdbc:
#  url: jdbc:kingbase8://127.0.0.1:5888/meetingdb
#  username: meetingdb
#  password: root123456
#  driver: com.kingbase8.Driver

## Shentong
#jdbc:
#  url: jdbc:oscar://127.0.0.1:2003/osrdb
#  username: meetingdb
#  password: root123456
#  driver: com.oscar.Driver

## nantong
#jdbc:
#  url: jdbc:gbase://127.0.0.1:5258/sealmeeting
#  username: sysdba
#  password: GBase8sV8316
#  driver: com.gbase.jdbc.Driver

ds:
  initialSize: 5
  minIdle: 10
  maxActive: 100
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000