server:
  port: 8081
  servlet:
    context-path: /api
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
      indent_output: true
      write_null_map_values: false
    deserialization:
      accept_single_value_as_array: true
    default-property-inclusion: non_null
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

## JWT 鉴权配置
jwt:
  secret: "ay9pL#$MeetingServer"
  ttlInMilliSec: 86400000

## 融云 IM 配置
im:
  appKey: xxx
  secret: xxxx
  host: http://api-cn.ronghub.com

## 融云 RCE 配置
rce:
  systemUid: xxx
  secret: xxx
  host: http://127.0.0.1/api

## 日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    cn.rongcloud: INFO
  file:
    max-history: 8
    name: logs/momentserver.log
    max-size: 100MB
  pattern:
    rolling-file-name: logs/momentserver.%d{yyyy-MM-dd}.%i.gz

# 数据库相关配置
db:
  name: mysql
# Mysql
jdbc:
  url: jdbc:mysql://localhost:3306/momentdb?useUnicode=true
  username: root
  password: 123456
  driver: com.mysql.jdbc.Driver

ds:
  initialSize: 5
  minIdle: 10
  maxActive: 100
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000


##moment工程内部配置

moment:
  pass:
    anonymousUrls: /**/*/moment/auth
  publish_notify_corn: 0 */1 * * * ?
  system_manager_id: xxxxxxxx #系统管理员Id

swagger2:
  enable: true