CREATE TABLE "T_COMMENT" (
                                    "ID" SERIAL NOT NULL,
                                    "COMMENT_ID" VARCHAR(100) NOT NULL,
    "FEED_ID" VARCHAR(100) NOT NULL,
    "USER_ID" VARCHAR(100) NOT NULL,
    "COMMENT_CONTENT" VARCHAR(4096),
    "REPLY_TO" VARCHAR(100),
    "CREATE_DT" TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY ("ID"),
    CONSTRAINT "UNIQUE_T_COMMENT_COMMENT_ID"  UNIQUE ("COMMENT_ID")
    )
     ;
CREATE INDEX "IDX_COMMENT_FID_UID" ON "T_COMMENT" ("FEED_ID","USER_ID");
CREATE TABLE "T_FEED" (
                                 "ID" SERIAL NOT NULL,
                                 "FEED_ID" VARCHAR(64) NOT NULL,
    "USER_ID" VARCHAR(64) NOT NULL,
    "FEED_TYPE" INTEGER NOT NULL,
    "FEED_CONTENT" VARCHAR(4096) NOT NULL,
    "FEED_POI" VARCHAR(255),
    "FEED_STATUS" INTEGER NOT NULL DEFAULT 0,
    "CREATE_DT" TIMESTAMP WITHOUT TIME ZONE,
    "UPDATE_DT" TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY ("ID"),
    CONSTRAINT "UNIQUE_T_FEED_FEED_ID" UNIQUE ("FEED_ID")
    )
     ;
CREATE TABLE "T_LIKE" (
                                 "ID" SERIAL NOT NULL,
                                 "LIKE_ID" VARCHAR(100) NOT NULL,
    "FEED_ID" VARCHAR(100) NOT NULL,
    "USER_ID" VARCHAR(100) NOT NULL,
    "CREATE_DT" TIMESTAMP WITHOUT TIME ZONE,
    "LIKE_STATUS" INTEGER NOT NULL,
    PRIMARY KEY ("ID"),
    CONSTRAINT "UNIQUE_T_LIKE_LIKE_ID" UNIQUE ("LIKE_ID"),
    CONSTRAINT "UNIQUE_T_LIKE_FEED_ID_USER_ID" UNIQUE ("FEED_ID","USER_ID")
    )
     ;
CREATE TABLE "T_MESSAGE" (
                                    "ID" SERIAL NOT NULL,
                                    "MESSAGE_ID" VARCHAR(64) NOT NULL,
    "FEED_ID" VARCHAR(64) NOT NULL,
    "USER_ID" VARCHAR(64) NOT NULL,
    "MESSAGE_TYPE" INTEGER NOT NULL,
    "STATUS" INTEGER NOT NULL,
    "CREATE_DT" TIMESTAMP WITHOUT TIME ZONE,
    "PUBLISH_USER_ID" VARCHAR(64) NOT NULL,
    PRIMARY KEY ("ID")
    )
     ;
CREATE INDEX "IDX_MESSAGE_USER_ID" ON  "T_MESSAGE"("USER_ID");
CREATE INDEX "IDX_MESSAGE_MESSAGE_ID" ON  "T_MESSAGE"("MESSAGE_ID");
CREATE TABLE "T_TIMELINE" (
                                     "ID" SERIAL NOT NULL,
                                     "FEED_ID" VARCHAR(32) NOT NULL,
    "ORG_ID" VARCHAR(32) NOT NULL,
    "CREATE_DT" TIMESTAMP WITHOUT TIME ZONE,
    "FEED_STATUS" INTEGER NOT NULL,
    PRIMARY KEY ("ID")
    )
     ;
CREATE INDEX "IDEX_TIMELINE_ORG_ID" ON  "T_TIMELINE"("ORG_ID");
CREATE INDEX "IDEX_TIMELINE_CREATE_DT" ON  "T_TIMELINE"("CREATE_DT");
CREATE TABLE "T_USER_SETTING" (
    "USER_ID" VARCHAR(100) NOT NULL,
    "COVER" VARCHAR(1024),
    "UPDATE_DT" TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY ("USER_ID")
    )
     ;

